config:
  arena-infra:workerName: arena-api-dev
  arena-infra:pagesProjectName: arena-web-dev
  arena-infra:kvNamespaceName: arena-kv-dev
  arena-infra:d1DatabaseName: arena-db-dev
  arena-infra:workerEnv: development
  # Run after cloning:
  #   pulumi config set --secret cloudflareAccountId <your-id> --stack dev
  #   pulumi config set --secret betterAuthSecret $(openssl rand -base64 32) --stack dev

  arena-infra:cloudflareAccountId:
    secure: AAABAEB/kWGn+IEcHYiUGNmOyaGe0QNjf9JmiV/T5BR/eox0rv2RW80eXvwmWz4lW77ykeyXWynNl6FModP1lQ==
  arena-infra:betterAuthSecret:
    secure: AAABAOq+x7+hfWSKxL8AaFyhkejqye5IpbqwMJtfIkZyA8Qg224rjzYy6nt+FXvg4VLNlSBDlwM7fgwmCJnp8YiB4TYnnUpUitymGQ==
  arena-infra:workersDevSubdomain: atharv-vaish
  arena-infra:betterAuthUrl: https://arena-api-dev.atharv-vaish.workers.dev
  arena-infra:passkeyRpId: arena-web-dev.pages.dev
  arena-infra:passkeyOrigin: https://arena-web-dev.pages.dev
